version: '3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  readingisgood:
    image:   readingisgood-v1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_DATABASE=readingisgood
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017



volumes:
  readingisgood: